### ISSUE TITLE
Add RecordRequester permissions group

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/pra-request-tracker#13]
From @sarayourfriend 

> I was thinking we could just create a user group, RecordRequester, who have permissions over adding agencies, record requests and record request files. Then users can register themselves on the site but whomever ends up being superadmin will just add whichever folks to that RecordRequester group

**Comment by sarayourfriend** [comment]
We'll just do this in the deployed application, right? (I don't think there's a code way to do it is there?)

**Comment by AetherUnbound** [comment]
Oh! I thought it was a programmatic thing we had to do with the models. We can just do this with the admin forms?

**Comment by sarayourfriend** [comment]
Yup! 
<img width="2032" alt="Captura de Tela 2021-07-05 às 19 09 11" src="https://user-images.githubusercontent.com/24264157/124531993-7cad6900-ddc4-11eb-959c-986343b1b6ed.png">

**Comment by AetherUnbound** [comment]
Oh dang! Well, I'll leave this issue open, but it doesn't require a code change :smile:

**Comment by AetherUnbound** [comment]
This is done!
